[target.thumbv7em-none-eabihf]
# runner = "arm-none-eabi-gdb.exe -q -x ../openocd.gdb"
runner = "gdb-multiarch -q -x ../openocd.gdb"
# runner = "gdb -q"
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabihf"

