[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "sht31d"
version = "0.1.0"

[dependencies]
m = "0.1.1"
aux98 = { path = "auxiliary" }
sht3x = { git = "https://github.com/sciguy16/sht3x-rs", branch = "borrow_delay"}
